name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main

permissions:
  contents: write
  pages: write
  id-token: write

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install dependencies
        run: npm install --legacy-peer-deps

      - name: Build Next.js app
        run: npm run build
        env:
          NEXT_PUBLIC_BASE_PATH: /${{ github.event.repository.name }}
          NEXT_PUBLIC_RECAPTCHA_SITE_KEY: ${{ secrets.NEXT_PUBLIC_RECAPTCHA_SITE_KEY }}
          NEXT_PUBLIC_EMAILJS_API_KEY: ${{ secrets.NEXT_PUBLIC_EMAILJS_API_KEY }}
          NEXT_PUBLIC_EMAILJS_SERVICE_KEY: ${{ secrets.NEXT_PUBLIC_EMAILJS_SERVICE_KEY }}
          NEXT_PUBLIC_EMAILJS_TEMPLATE_KEY: ${{ secrets.NEXT_PUBLIC_EMAILJS_TEMPLATE_KEY }}
          NEXT_PUBLIC_WHATSAPP: ${{ secrets.NEXT_PUBLIC_WHATSAPP }}
          NEXT_PUBLIC_FACEBOOK: ${{ secrets.NEXT_PUBLIC_FACEBOOK }}
          NEXT_PUBLIC_EMAIL: ${{ secrets.NEXT_PUBLIC_EMAIL }}

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./out
          force_orphan: true
          user_name: "github-actions[bot]"
          user_email: "github-actions[bot]@users.noreply.github.com"
