name: Deploy to Siteworx

on:
  push:
    branches:
      - main

permissions:
  contents: write
  id-token: write

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install dependencies
        run: npm install --legacy-peer-deps

      - name: Build Next.js app
        run: npm run build
        env:
          NEXT_PUBLIC_RECAPTCHA_SITE_KEY: ${{ secrets.NEXT_PUBLIC_RECAPTCHA_SITE_KEY }}
          NEXT_PUBLIC_EMAILJS_API_KEY: ${{ secrets.NEXT_PUBLIC_EMAILJS_API_KEY }}
          NEXT_PUBLIC_EMAILJS_SERVICE_KEY: ${{ secrets.NEXT_PUBLIC_EMAILJS_SERVICE_KEY }}
          NEXT_PUBLIC_EMAILJS_TEMPLATE_KEY: ${{ secrets.NEXT_PUBLIC_EMAILJS_TEMPLATE_KEY }}
          NEXT_PUBLIC_WHATSAPP: ${{ secrets.NEXT_PUBLIC_WHATSAPP }}
          NEXT_PUBLIC_FACEBOOK: ${{ secrets.NEXT_PUBLIC_FACEBOOK }}
          NEXT_PUBLIC_EMAIL: ${{ secrets.NEXT_PUBLIC_EMAIL }}
          NEXT_PUBLIC_BASE_PATH: ${{ secrets.NEXT_PUBLIC_BASE_PATH }}

      - name: Deploy to Siteworx
        uses: SamKirkland/FTP-Deploy-Action@v4.3.4
        with:
          server: ${{ secrets.SITEWORX_FTP_SERVER }}
          username: ${{ secrets.SITEWORX_FTP_USERNAME }}
          password: ${{ secrets.SITEWORX_FTP_PASSWORD }}
          local-dir: ./out/
          server-dir: ${{ secrets.SITEWORX_SERVER_DIR }}
